# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  NeuronTest_config = debug
  LayerTest_config = debug
endif
ifeq ($(config),release)
  NeuronTest_config = release
  LayerTest_config = release
endif

PROJECTS := NeuronTest LayerTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

NeuronTest:
ifneq (,$(NeuronTest_config))
	@echo "==== Building NeuronTest ($(NeuronTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f NeuronTest.make config=$(NeuronTest_config)
endif

LayerTest:
ifneq (,$(LayerTest_config))
	@echo "==== Building LayerTest ($(LayerTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f LayerTest.make config=$(LayerTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f NeuronTest.make clean
	@${MAKE} --no-print-directory -C . -f LayerTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NeuronTest"
	@echo "   LayerTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"