# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Synapse_config = debug
  NeuronTest_config = debug
endif
ifeq ($(config),release)
  Synapse_config = release
  NeuronTest_config = release
endif

PROJECTS := Synapse NeuronTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Synapse:
ifneq (,$(Synapse_config))
	@echo "==== Building Synapse ($(Synapse_config)) ===="
	@${MAKE} --no-print-directory -C . -f Synapse.make config=$(Synapse_config)
endif

NeuronTest:
ifneq (,$(NeuronTest_config))
	@echo "==== Building NeuronTest ($(NeuronTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f NeuronTest.make config=$(NeuronTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Synapse.make clean
	@${MAKE} --no-print-directory -C . -f NeuronTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Synapse"
	@echo "   NeuronTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"